
package view;

import java.util.Iterator;

import javax.swing.table.DefaultTableModel;

import model.Alumno;
import model.Cursada;
import model.Profesor;

@SuppressWarnings("serial")
public class VCursadaConsulta extends javax.swing.JFrame
{
    
    private static VCursadaConsulta ventanaCursadaConsulta = null;

    /** Creates new form VCursadaConsulta */
    private VCursadaConsulta()
    {
        initComponents();
        this.addWindowListener(WindowSerializador.getInstance());
    }

    public static VCursadaConsulta getInstance(Cursada cursada)
    {
        if (ventanaCursadaConsulta == null)
            ventanaCursadaConsulta = new VCursadaConsulta();
        ventanaCursadaConsulta.setComponentes(cursada);
        return ventanaCursadaConsulta;
    }

    public void setComponentes(Cursada cursada)
    {
        this.addWindowListener(WindowSerializador.getInstance());
        jTextFieldIdentificador.setText(cursada.getId());
        jTextFieldAsignatura.setText(cursada.getAsignatura().getNombre());
        jTextFieldPeriodo.setText(cursada.getPeriodo());
        jTextFieldDia.setText(cursada.getDia());
        jTextFieldHoraInicio.setText(cursada.getHoraInicio());
        jTextFieldHoraFin.setText(cursada.getHoraFin());
        setTablaProfesores(cursada);
        setTablaAlumnos(cursada);
    }

    private void setTablaProfesores(Cursada cursada)
    {
        DefaultTableModel model = (DefaultTableModel) jTableProfesores.getModel();
        model.setRowCount(0);
        Iterator<Profesor> profesores = cursada.getProfesoresIterator();
        while (profesores.hasNext())
        {
            Profesor profesor = profesores.next();
            model.addRow(new Object[] { profesor.getId(), profesor.getNombre(), profesor.getApellido() });
        }
    }

    private void setTablaAlumnos(Cursada cursada)
    {
        DefaultTableModel model = (DefaultTableModel) jTableAlumnos.getModel();
        model.setRowCount(0);
        Iterator<Alumno> alumnos = cursada.getAlumnosIterator();
        while (alumnos.hasNext())
        {
            Alumno alumno = alumnos.next();
            model.addRow(new Object[] { alumno.getId(), alumno.getNombre(), alumno.getApellido() });
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jPanelCabecera = new javax.swing.JPanel();
        jLabelCursada = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jLabelConsulta = new javax.swing.JLabel();
        jPanelGrilla = new javax.swing.JPanel();
        jLabelIdentificador = new javax.swing.JLabel();
        jLabelNAsignatura = new javax.swing.JLabel();
        jLabelPeriodo = new javax.swing.JLabel();
        jLabelDia = new javax.swing.JLabel();
        jLabelProfesores = new javax.swing.JLabel();
        jTextFieldIdentificador = new javax.swing.JTextField();
        jTextFieldAsignatura = new javax.swing.JTextField();
        jTextFieldPeriodo = new javax.swing.JTextField();
        jLabelHoraFin = new javax.swing.JLabel();
        jTextFieldHoraFin = new javax.swing.JTextField();
        jScrollPaneProfesores = new javax.swing.JScrollPane();
        jTableProfesores = new javax.swing.JTable();
        jLabelHoraInicio = new javax.swing.JLabel();
        jTextFieldHoraInicio = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jLabelAlumnos = new javax.swing.JLabel();
        jScrollPaneAlumnos = new javax.swing.JScrollPane();
        jTableAlumnos = new javax.swing.JTable();
        jTextFieldDia = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cursada - Consulta");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanelCabecera.setBackground(new java.awt.Color(204, 255, 255));
        jPanelCabecera.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabelCursada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelCursada.setText("Cursada -");

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Imagenes/aa0c19c7-d3a7-43d8-8664-2f08e5d0ca90.png"))); // NOI18N

        jLabelConsulta.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabelConsulta.setForeground(new java.awt.Color(102, 102, 102));
        jLabelConsulta.setText("Consulta");

        javax.swing.GroupLayout jPanelCabeceraLayout = new javax.swing.GroupLayout(jPanelCabecera);
        jPanelCabecera.setLayout(jPanelCabeceraLayout);
        jPanelCabeceraLayout.setHorizontalGroup(
            jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabelCursada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanelCabeceraLayout.setVerticalGroup(
            jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabeceraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCursada)
                    .addComponent(jLabelConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelCabecera, java.awt.BorderLayout.PAGE_START);

        jPanelGrilla.setBackground(new java.awt.Color(105, 255, 204));
        jPanelGrilla.setPreferredSize(new java.awt.Dimension(638, 618));
        jPanelGrilla.setVerifyInputWhenFocusTarget(false);

        jLabelIdentificador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIdentificador.setText("Identificador");

        jLabelNAsignatura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNAsignatura.setText("Asignatura");

        jLabelPeriodo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelPeriodo.setText("Periodo");

        jLabelDia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDia.setText("Dia");

        jLabelProfesores.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelProfesores.setText("Profesores");

        jTextFieldIdentificador.setEditable(false);
        jTextFieldIdentificador.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextFieldAsignatura.setEditable(false);

        jTextFieldPeriodo.setEditable(false);

        jLabelHoraFin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelHoraFin.setText("Hora Fin");

        jTextFieldHoraFin.setEditable(false);
        jTextFieldHoraFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoraFinActionPerformed(evt);
            }
        });

        jTableProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre", "Apellido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneProfesores.setViewportView(jTableProfesores);
        if (jTableProfesores.getColumnModel().getColumnCount() > 0) {
            jTableProfesores.getColumnModel().getColumn(0).setHeaderValue("Identificador");
            jTableProfesores.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            jTableProfesores.getColumnModel().getColumn(2).setHeaderValue("Apellido");
        }

        jLabelHoraInicio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelHoraInicio.setText("Hora Inicio");

        jTextFieldHoraInicio.setEditable(false);

        jButtonCancelar.setBackground(new java.awt.Color(0, 153, 153));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancelar.setText("SALIR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabelAlumnos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelAlumnos.setText("Alumnos");

        jTableAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Nombre", "Apellido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPaneAlumnos.setViewportView(jTableAlumnos);
        if (jTableAlumnos.getColumnModel().getColumnCount() > 0) {
            jTableAlumnos.getColumnModel().getColumn(0).setHeaderValue("Identificador");
            jTableAlumnos.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            jTableAlumnos.getColumnModel().getColumn(2).setHeaderValue("Apellido");
        }

        jTextFieldDia.setEditable(false);

        javax.swing.GroupLayout jPanelGrillaLayout = new javax.swing.GroupLayout(jPanelGrilla);
        jPanelGrilla.setLayout(jPanelGrillaLayout);
        jPanelGrillaLayout.setHorizontalGroup(
            jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrillaLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabelIdentificador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelPeriodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelHoraInicio)
                    .addComponent(jLabelProfesores)
                    .addComponent(jLabelAlumnos))
                .addGap(41, 41, 41)
                .addGroup(jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGrillaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCancelar)
                        .addGap(160, 160, 160))
                    .addGroup(jPanelGrillaLayout.createSequentialGroup()
                        .addGroup(jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPaneAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPaneProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelGrillaLayout.createSequentialGroup()
                                .addGroup(jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextFieldPeriodo, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(jTextFieldHoraInicio)
                                    .addComponent(jTextFieldIdentificador))
                                .addGap(30, 30, 30)
                                .addGroup(jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelGrillaLayout.createSequentialGroup()
                                        .addComponent(jLabelNAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldAsignatura, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                                    .addGroup(jPanelGrillaLayout.createSequentialGroup()
                                        .addGroup(jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelHoraFin)
                                            .addComponent(jLabelDia))
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldHoraFin, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                            .addComponent(jTextFieldDia))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelGrillaLayout.setVerticalGroup(
            jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrillaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNAsignatura)
                    .addComponent(jTextFieldAsignatura, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPeriodo)
                    .addComponent(jTextFieldPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDia)
                    .addComponent(jTextFieldDia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoraInicio)
                    .addComponent(jTextFieldHoraInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHoraFin)
                    .addComponent(jTextFieldHoraFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelProfesores))
                .addGap(31, 31, 31)
                .addGroup(jPanelGrillaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAlumnos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanelGrilla, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jTextFieldHoraFinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoraFinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoraFinActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        VentanaIndex.getInstancia().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabelAlumnos;
    private javax.swing.JLabel jLabelConsulta;
    private javax.swing.JLabel jLabelCursada;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelHoraFin;
    private javax.swing.JLabel jLabelHoraInicio;
    private javax.swing.JLabel jLabelIdentificador;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNAsignatura;
    private javax.swing.JLabel jLabelPeriodo;
    private javax.swing.JLabel jLabelProfesores;
    private javax.swing.JPanel jPanelCabecera;
    private javax.swing.JPanel jPanelGrilla;
    private javax.swing.JScrollPane jScrollPaneAlumnos;
    private javax.swing.JScrollPane jScrollPaneProfesores;
    private javax.swing.JTable jTableAlumnos;
    private javax.swing.JTable jTableProfesores;
    private javax.swing.JTextField jTextFieldAsignatura;
    private javax.swing.JTextField jTextFieldDia;
    private javax.swing.JTextField jTextFieldHoraFin;
    private javax.swing.JTextField jTextFieldHoraInicio;
    private javax.swing.JTextField jTextFieldIdentificador;
    private javax.swing.JTextField jTextFieldPeriodo;
    // End of variables declaration//GEN-END:variables

}
